name: test-on-push

on: [push]

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Install libsodium, a dependency of python-xeddsa
      shell: bash
      run: |
        curl -o libsodium-1.0.18-stable-msvc.zip https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip
        unzip libsodium-1.0.18-stable-msvc.zip

    - name: Run cmake
      shell: bash
      run: |
        export sodium_DIR="$(pwd)/libsodium/"
        mkdir build/
        cd build/
        cmake -T host=x64 -A x64 ..

    - name: Run MSBuild
      run: |
        cd build
        msbuild libxeddsa.sln

    - name: Run ctest in Debug configuration
      run: |
        cd build
        ctest -C Debug ..

    - name: Run ctest in Release configuration
      run: |
        cd build
        ctest -C Release ..

    - name: Rename the binaries
      run: |
        cd bin/
        mv combined_static.lib  libxeddsa-windows-amd64.lib
        mv combined_dynamic.lib libxeddsa-windows-amd64.dll.lib
        mv combined_dynamic.dll libxeddsa-windows-amd64.dll

    - name: Upload the binaries
      uses: actions/upload-artifact@v3.1.1
      with:
        name: binaries-windows
        path: |
          bin/libxeddsa-windows-amd64.lib
          bin/libxeddsa-windows-amd64.dll.lib
          bin/libxeddsa-windows-amd64.dll

  build-ubuntu-macos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install libsodium, a dependency of python-xeddsa, on ubuntu-latest
      run: sudo apt-get install -y libsodium-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Install libsodium, a dependency of python-xeddsa, on macos-latest
      run: brew install libsodium
      if: matrix.os == 'macos-latest'

    - name: Run cmake
      run: |
        mkdir build/
        cd build/
        FORCE_URANDOM= cmake ..

    - name: Run make
      run: |
        cd build/
        make

    - name: Run ctest
      run: |
        cd build/
        ctest ..

    - name: Rename the binaries on ubuntu-latest
      run: |
        cd bin/
        mv libcombined_static.a   libxeddsa-linux-amd64.a
        mv libcombined_dynamic.so libxeddsa-linux-amd64.so
      if: matrix.os == 'ubuntu-latest'

    - name: Rename the binaries on macos-latest
      run: |
        cd bin/
        mv libcombined_static.a      libxeddsa-macos-amd64.a
        mv libcombined_dynamic.dylib libxeddsa-macos-amd64.dylib
      if: matrix.os == 'macos-latest'

    - name: Upload the binaries on ubuntu-latest
      uses: actions/upload-artifact@v3.1.1
      with:
        name: binaries-ubuntu
        path: |
          bin/libxeddsa-linux-amd64.a
          bin/libxeddsa-linux-amd64.so
      if: matrix.os == 'ubuntu-latest'

    - name: Upload the binaries on macos-latest
      uses: actions/upload-artifact@v3.1.1
      with:
        name: binaries-macos
        path: |
          bin/libxeddsa-macos-amd64.a
          bin/libxeddsa-macos-amd64.dylib
      if: matrix.os == 'macos-latest'
