name: test-on-push

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install libsodium, a dependency of python-xeddsa, on ubuntu-latest
      run: sudo apt-get install -y libsodium-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Install libsodium, a dependency of python-xeddsa, on macos-latest
      run: brew install libsodium
      if: matrix.os == 'macos-latest'

    - name: Install libsodium, a dependency of python-xeddsa, on windows-latest
      shell: bash
      run: |
        curl -o libsodium-1.0.18-stable-msvc.zip https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-msvc.zip
        unzip libsodium-1.0.18-stable-msvc.zip
      if: matrix.os == 'windows-latest'

    - name: Run cmake on ubuntu-lastest or macos-latest
      run: |
        mkdir build/
        cd build/
        cmake ..
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

    - name: Run cmake on windows-lastest
      shell: bash
      run: |
        export sodium_DIR="$(pwd)/libsodium/"
        mkdir build/
        cd build/
        cmake -T host=x64 -A x64 ..
      if: matrix.os == 'windows-latest'

    - name: Run make on ubuntu-lastest or macos-latest
      shell: bash
      run: |
        cd build/
        make
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

    - name: Setup MSBuild on windows-latest
      uses: microsoft/setup-msbuild@v1.1.3
      if: matrix.os == 'windows-latest'

    - name: Run MSBuild on windows-lastest
      run: |
        cd build
        msbuild libxeddsa.sln
      if: matrix.os == 'windows-latest'

    - name: Run ctest
      shell: bash
      run: |
        cd build/
        ctest ..
